# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

    # React Native Android Build APK
    - name: React Native Android Build APK
      uses: realabbas/Github-Actions-React-Native@v1.1.2

    - name: iOS Build Action
      uses: yukiarrr/ios-build-action@v0.5.1
      with:
        # Project path
        project-path: 
        # Base64 encoded p12 file
        p12-base64: 
        # Base64 encoded mobileprovision file
        mobileprovision-base64: 
        # For example, iOS Distribution
        code-signing-identity: 
        # Team id
        team-id: 
        # Workspace path
        workspace-path: # optional, default is 
        # Choose app-store, ad-hoc, package, enterprise, development, or developer-id
        export-method: # optional, default is app-store
        # For example, Debug, Release
        configuration: # optional, default is Release
        # Certificate password
        certificate-password: # optional, default is 
        # Output path of ipa
        output-path: # optional, default is output.ipa
        # Scheme
        scheme: # optional, default is 

